/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaiHinh2;

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

/**
 * NHT
 */
public class App {
    public static void main(String[] args) throws IOException, InterruptedException {

        Document doc = Jsoup.connect("https://kissmanga.org/chapter/manga-ee981361/chapter-1").timeout(20000).get();
        List<String> img = new ArrayList<>();
        Elements im = doc.getElementsByTag("img");
        for (int i = 0; i < im.size(); i++) {
            String url = im.get(i).absUrl("src");
            if (url.equals("")) {
                continue;
            }
            if (url.contains("blazefast")) {
                img.add(url);
            }
        }

        PrintWriter pw = new PrintWriter(new File("link.txt"));
        pw.print(img);
        pw.close();
        taiAnh(img);
    }

    public static void taiAnh(List<String> img) throws IOException, InterruptedException {
        ThreadPoolExecutor e = (ThreadPoolExecutor) (Executors.newFixedThreadPool(10));

        for (int a = 0; a < img.size(); a++) {
            String name = (a + 1) + ".jpg";
            String link = img.get(a);
            Thread01 t1 = new Thread01(name, link);
            e.submit(t1);
        }
        e.shutdown();
        e.awaitTermination(1, TimeUnit.MINUTES);
    }
}
